# project-wide settings
destination: _site

title:            Kraig Walker
description:      Design And Code Converge
logo:             site-logo.jpg
disqus_shortname: kraigwalker
#Comment out url when working locally to resolve base urls correctly
url: http://kraigwalker.com

# Owner/author information
owner:
  name:           Kraig Walker
  avatar:         kraig_walker.jpg
  email:          kraig_walker@me.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        Kraig_Walker
  facebook:       kraig.walker
  github:         KraigWalker
  linkedin:       kraigwalker
  instagram:      kraig_walker
  flickr:
  tumblr:         kraigwalker
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/104694977517220407329

# Analytics and webmaster tools stuff goes here
google_analytics: UA-19175832-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 52B2C4BFDAB8A150CB001541CA925A62
fb_app_id:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Index
    url: /
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  coderay:
    coderay_css: class
    coderay_line_numbers: ''

include: [".htaccess, .deployment"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]