title:            Kraig Walker
description:      Describe your website here.
logo:             site-logo.png
disqus_shortname:
#Comment out url when working locally to resolve base urls correctly
#url:              kraigwalker.github.io

# Owner/author information
owner:
  name:           Kraig Walker
  avatar:         bio-photo.jpg
  email:          kraig_walker@me.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        Kraig_Walker
  facebook:
  github:         https://github.com/KraigWalker
  stackexchange:  http://stackoverflow.com/users/2463810/kraig-walker
  linkedin:       http://lnkd.in/5AcEwN
  instagram:      https://instagram.com/kraigwalker
  flickr:
  tumblr:         http://kraigwalker.tumblr.com
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/104694977517220407329

# Analytics and webmaster tools stuff goes here
google_analytics: UA-19175832-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles
  - title: Theme Setup
    url: /theme-setup
  - title: Made Mistakes
    url: http://mademistakes.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]